#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00
#PBS -l vmem=20gb

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_dir_report

singularity exec docker://brainlife/mne:0.23dev python3 main.py
