#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:00:00
#PBS -l vmem=20gb

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_dir_report
#mkdir -p out_dir2

# Install necessary libraries
singularity exec --env FS_LICENSE=${FS_LICENSE} -e docker://brainlife/mne-freesurfer:7.3.2-1.2.1 pip install pyqt5 pyvistaqt ipywidgets

#singularity exec docker://brainlife/mne:0.23dev python3 main.py
singularity exec --env FS_LICENSE=${FS_LICENSE} -e docker://brainlife/mne-freesurfer:7.3.2-1.2.1 xvfb-run -a python3 main.py