#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:00:00
#PBS -l vmem=20gb

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_dir_report
#mkdir -p out_dir2

#singularity exec docker://brainlife/mne:0.23dev python3 main.py
singularity exec docker://brainlife/mne:1.2.1 python3 main.py